#version: "3.8"
#services:
  #mobylab-app-db:
    #image: postgres:13.2-alpine
    #ports:
      #- "5432:5432"
    #environment:
      #POSTGRES_USER: postgres
      #POSTGRES_DB: postgres
      #POSTGRES_PASSWORD: postgres
    #volumes:
      #- mobylab-app-db-vol:/var/lib/postgresql/data

  #auth:
    #build: .
    #depends_on:
      #- mobylab-app-db
    #ports:
      #- "8081:8090"
    #environment:
      #SPRING_PROFILES_ACTIVE: auth
      #SPRING_DATASOURCE_URL: jdbc:postgresql://mobylab-app-db:5432/postgres
      #SPRING_DATASOURCE_USERNAME: postgres
      #SPRING_DATASOURCE_PASSWORD: postgres

  #backend:
    #build: .
    #depends_on:
      #- mobylab-app-db
      #- auth
    #ports:
      #- "8080:8090"
    #environment:
      #SPRING_PROFILES_ACTIVE: backend
      #SPRING_DATASOURCE_URL: jdbc:postgresql://mobylab-app-db:5432/postgres
      #SPRING_DATASOURCE_USERNAME: postgres
      #SPRING_DATASOURCE_PASSWORD: postgres

#volumes:
  #mobylab-app-db-vol:


version: "3.8"
services:
  mobylab-app-db:
    image: postgres:13.2-alpine
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - mobylab-app-db-vol:/var/lib/postgresql/data
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure

  auth:
    image: ivvlad/auth-service-idp-ivv-imm:latest # Replace this with your actual built image
    #depends_on:
      #- mobylab-app-db
    ports:
      - "8081:8090"
    environment:
      SPRING_PROFILES_ACTIVE: auth
      SPRING_DATASOURCE_URL: jdbc:postgresql://mobylab-app-db:5432/postgres
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: postgres
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure

  backend:
    image: ivvlad/backend-service-idp-ivv-imm:latest # Replace this with your actual built image
    #depends_on:
      #- mobylab-app-db
      #- auth
    ports:
      - "8080:8090"
    environment:
      SPRING_PROFILES_ACTIVE: backend
      SPRING_DATASOURCE_URL: jdbc:postgresql://mobylab-app-db:5432/postgres
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: postgres
    deploy:
      replicas: 2 # You can adjust the number of replicas
      restart_policy:
        condition: on-failure

volumes:
  mobylab-app-db-vol:
